### ISSUE TITLE
indirect eval fails

### ISSUE THREAD

**Issue by michaelfig** [Agoric/realms-shim#25]
Note that with the current implementation of realms-shim, adding the following test case to `test/module/evaluators.js`:

```js
t.equal(safeEval(`(1,eval)('123')`), 123, 'indirect eval');
```

fails with:

```
TypeError: (1 , eval) is not a function
```

It also fails with the exported `r.evaluate()` function.

This failure seems wrong to me.  Shouldn't indirect eval of this form be supported?

**Comment by erights** [comment]
You are correct that this should have worked. I am surprised that it did not. Definitely a bug. Please file issue. Tag security relevant. Curious to find out what the problem is?
