### ISSUE TITLE
evaluate publishing this package into npm

### ISSUE THREAD

**Issue by caridy** [Agoric/realms-shim#29]

**Comment by caridy** [comment]
we were hoping to discuss this on the meeting today, but it was canceled. any opinions here? I don't remember if in this past we discussed this, so I see no problems with publishing the shim into different registries to facilitate their usage. cc @erights @jdalton

**Comment by erights** [comment]
I support publishing it to npm. It is useful, and used, as is. We should document changes we expect to make, but this will always be true.

**Comment by caridy** [comment]
maybe @jdalton can take care of the clean up and get this ready to publish it.

**Comment by jdalton** [comment]
I'll give things a review/cleanup in prep for publishing 👍

**Comment by warner** [comment]
The realms-shim has been [published to NPM](https://www.npmjs.com/package/realms-shim) as version 1.1.0 (provoked by #48). That release doesn't include everything from #40, so the next step is to finish up #40 and merge it, then make a 1.1.1 release.
