### ISSUE TITLE
per-evaluate options.sloppyGlobals

### ISSUE THREAD

**Issue by michaelfig** [Agoric/realms-shim#31]
#30 introduced a root realm/compartment option called `sloppyGlobals`.  It would be advantageous if this option could also be specified per-evaluation.

@erights, @kumavis, I need help deciding on implementation.  The only options I see thus far for passing this kind of modification down to the `scopeHandler` (which is the code that decides if a sloppy global can be assigned) are:

1. Indirect the creation of the scopeHandler so that it becomes a factory that is called per-evaluation instead of just once per compartment.  This to me seems cleaner, but is a more drastic change.
2. Create a source-code-inaccessible property (like a key that begins with a digit, yuck) on the scopeTarget (where the endowments are), and have the scopeHandler use it to determine behaviour.

And finally, should the per-evaluate option override the compartment option?  I think it should.

Thoughts?

**Comment by erights** [comment]
Definitely not (2. Create...). (1.Indirect...) seems fine.

Yes, per-evaluate should shadow the per compartment settings.

**Comment by michaelfig** [comment]
This feature was discussed and discarded.  Instead, we should just have the per-compartment/non-frozen-root-realm flag.

Closing for now.
